version: "3.8"
services: 
  todo-list:
    container_name: todo-list
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes: 
      - "./:/usr/src/app"
    ports: 
      - 3000:3000
      - 9339:9339